---
- name: dynatrace demo
  hosts: all
  sources:
    - name: alertmanager
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5050
  
  rules:
    - name: Service http is not running on  web server 
      condition:    event.payload.message == "iniciar"
      action:
        run_job_template:
          name: "iniciar-apache"
          organization: "Default"
...
