---
- name: dynatrace demo
  hosts: all
  sources:
    - name: alertmanager
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5050
  
  rules:
    - name: Dynatrace volver a iniciar servicio httpd 1
      condition:    event.payload.message == "iniciar"
      action:
        run_job_template:
          name: "iniciar-apache"
          organization: "Default"
    - name: Dynatrace volver a iniciar servicio httpd 2
      condition:    event.payload.message == "State":"OPEN"
      action:
        run_job_template:
          name: "iniciar-apache"
          organization: "Default"
...
