---
- name: Hello Events
  hosts: all
  sources:
    - dynatrace.eda.dt_esa_api:
        dt_api_host: 5
  rules:
    - name: Say Hello
      condition: event.i == 1
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
...
