---
- name: dynatrace demo
  hosts: all
  sources:
    - name: alertmanager
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path:
        data_host_path: ImpactedEntityNames
        skip_original_data: true
      filters:
        - ansible.eda.json_filter:
            exclude_keys:
              - ProblemDetailsMarkdown
              - ProblemDetailsText
              - ProblemDetailsJSON

  rules:
    - name: Service http is not running on  web server 
      condition: event.payload.problemTitle contains "Http monitor global outage"
      action:
        run_job_template:
          name: "iniciar-apache"
          organization: "Default"
...
