---
- name: Controller Demo
  hosts: all
  sources:
    - dynatrace.eda.dt_esa_api:
        dt_api_host: "https://dyx62030.apps.dynatrace.com" 
        dt_api_token: "{{ dyna_token }}.
        delay: 1
  rules:

    - name: Service http is not running on  web server 
      condition: event.payload.problemTitle contains "Http monitor global outage"
      action:
        run_job_template:
          name: "iniciar-apache"
          organization: "Default"

...

